name: Run All Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run Unit tests
        run: |
          if [ -f bin/phpunit ]; then php bin/phpunit --testdox;
          else vendor/bin/phpunit --testdox; fi

      - name: Run End-to-End tests
        run: |
          php -S 127.0.0.1:8000 -t public >/dev/null 2>&1 &
          sleep 5
          php tests/EndToEnd/run-tests.php
