name: Run All Tests
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit ^10

      - name: Run Unit tests
        run: vendor/bin/phpunit --testdox

      - name: Run End-to-End tests
        run: |
          php artisan serve &
          sleep 5
          php tests/e2e/run-tests.php
