name: Quality Gate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  run-tests:
    name: Run Symfony Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose up -d php db

      - name: Install Composer dependencies
        run: docker compose exec -T php bash -c "cd /var/www/app && composer install --no-interaction --prefer-dist --optimize-autoloader"

      - name: Copy CI environment
        run: docker compose exec -T php bash -c "cd /var/www/app && cp .env.ci .env"

      - name: Run database migrations
        run: docker compose exec -T php bash -c "cd /var/www/app && php bin/console doctrine:migrations:migrate --no-interaction"

      - name: Run Symfony tests (PHPUnit)
        run: docker compose exec -T php bash -c "cd /var/www/app && ./vendor/bin/phpunit"
