name: Run All Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run Unit tests
  run: |
    if [ -f bin/phpunit ]; then php bin/phpunit --testdox tests/Unit;
    else vendor/bin/phpunit --testdox tests/Unit; fi

     - name: Run End-To-End tests
  run: |
    if [ -f bin/phpunit ]; then php bin/phpunit --testdox tests/EndToEnd;
    else vendor/bin/phpunit --testdox tests/EndToEnd; fi
